### ISSUE TITLE
Last week 1752 percent of your users were first time visitors.

### ISSUE THREAD

**Issue by joehorning** [EMRL/stir#115]
What type of report is this:

| Q  | A
| ---| ---
| Bug report? | X
| Feature request? | 
| Enhancement? | 

## Description:
Comes out in digest stats.

## If a bug:

| Q   | A
| --- | ---
| Deploy version | [3.6.5] - 11-17-2017

### Steps to reproduce:
1. May have been already fixed in commit https://github.com/EMRL/deploy/commit/9cfade4cbad6b2725dba001f045f4869902905fb
2. 
 
### Log errors: 

_Please check for related errors in your log files._

**Comment by fdiebel** [comment]
https://github.com/EMRL/deploy/commit/9cfade4cbad6b2725dba001f045f4869902905fb already fixed this.

This was the result of CAA's new ad system returning weird session numbers. I added a function to make sure now percentage ever exceeds 100.
