### ISSUE TITLE
The Basics section (.stir.sh)

### ISSUE THREAD

**Issue by halinkodev** [EMRL/stir#162]
Make a "The Basics" section in .stir.sh for people who just wanna bare bones configuration

**Comment by fdiebel** [comment]
Working on adding self-configuration on project start up. Should be able to get the min. info into `.stir.sh` automatically; min. info will be

1. Project name (maybe use current directory name for this)
2. Repo host URL
3. Repo name
4. "Master" branch (will prolly just use current branch)

User will be prompted to confirm or override these 4 values, should be enough to get things rolling

I think this approach will work better than messing w/ the config file structure

**Comment by fdiebel** [comment]
Considering this closed and dealt with, bare bones per-project config will be handled via another issue
