### ISSUE TITLE
Attempt to repair files? (sudo required) [Y/n] - n weirdness...

### ISSUE THREAD

**Issue by joehorning** [EMRL/stir#52]
`Wordfence firewall detected, and may cause issues with deployment.
Attempt to repair files? (sudo required) [Y/n]
`

I answered "n" then this happened...

`Deployment can not continue while Wordfence firewall is enabled.
rm: remove write-protected regular file ‘/var/www/production/deploy/kyhca42a155.html’? 
Wordfence firewall detected, and may cause issues with deployment.
Attempt to repair files? (sudo required) [Y/n] n
Deployment can not continue while Wordfence firewall is enabled.
rm: remove write-protected regular file ‘/var/www/production/deploy/kyhca42a155.html’?
rm: remove write-protected regular file ‘/var/www/production/deploy/rfbiocidicscff46f8.html’? 
rm: remove write-protected regular file ‘/var/www/production/deploy/caa8260661.html’? 
rm: remove write-protected regular file ‘/var/www/production/deploy/mcorp-ERROR-20146.html’? 
rm: remove write-protected regular file ‘/var/www/production/deploy/tricountyjobfair77bd1da.html’?
`

**Comment by fdiebel** [comment]
Closing this until if/when we ever see it again and can diagnose the issue a bit more clearly
