### ISSUE TITLE
"lynx: Can't access start file" @ end of deploy script

### ISSUE THREAD

**Issue by joehorning** [EMRL/stir#54]
'deploy 3.5.5
Current working path is /var/www/html/greyrock
Continue? [Y/n]

Checking servers...
 https://bitbucket.org/emrl/greyrock-web/ OK
 greyrock.emrl.mx (development) OK

Preparing repository...
Counting objects: 5812, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (4592/4592), done.
Writing objects: 100% (5812/5812), done.
Total 5812 (delta 1118), reused 5812 (delta 1118)

Checking for updates...
The following updates are available:
  advanced-custom-fields-pro 5.5.7
  backwpup 3.3.6
  ewww-image-optimizer 3.2.6
  google-analytics-dashboard-for-wp 4.9.6.1
  gravityforms 2.1.3
  relevanssi 3.5.8
  wordfence 6.3.1
  wordpress-seo 4.3

Proceed with updates? [y/N] y
Plugin updates complete.

A new version of Wordpress is available (4.7.2), update? [y/N] y
Wordpress core updates complete.
Upgrading development database...

Found npm configuration!
Build assets? [y/N]
Skipping Node Package Manager...

Stage files? [Y/n]

Edit commit message: Updated 7 of 7 plugins (advanced-custom-fields-pro 5.5.7, backwpup 3.3.6, ewww-image-optimizer 3.2.6, google-analytics-dashboard-for-wp 4.9.6.1, gravityforms 2.1.3, relevanssi 3.5.8, wordfence 6.3.1, wordpress-seo 4.3) and system (wp-core 4.7.2)

Push master branch? [Y/n]
Success.

Upgrading production database...

Can't Access `file://localhost/system/wp-admin/upgrade.php?step=1'
Alert!: Unable to access document.

lynx: Can't access startfile
Calculating...
Your total lines of code contributed so far: 1111462
(+1135845 added | -24383 deleted)
Deployment Success.
Exiting.
'

**Comment by fdiebel** [comment]
Should be fixed. Production db will now be upgraded when 

1. core is updated
2. production branch is defined
3. production URL is defined 
4. deployment exists
